### ISSUE TITLE
api: stabilise and document

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-mail#16]
- [x] check existing API functionality
  - [ ]  The task has no realistic integration test #11 
- [x] add missing important API functionality
- [x] check API function signatures and parameters
- [x] enhance API docstrings (`param`, `returns`, `raises`, `versionadded`)
- [x] plug API functions to existing docs

**Comment by lnielsen** [comment]
Closed by 81efd1d58ed534c79fbf1ac3d1674dfdf5b98cfe
