### ISSUE TITLE
api: helper for sending templated messages

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-mail#19]
- [ ] set base template for emails `BASE_MAIL_TEMPLATE`
- [ ] create `TemplatedMessage` helper class (`__init__/create(self/cls, template_name, ctx=None, **kwargs)`) 
  - possible usage `TemplatedMessage.create('account_enabled.html', ctx={'user': user}, subject=_('...'), ...)`
  - set `.body` and `.html` on `Message` instance

**Comment by remileduc** [comment]
We talked with @lnielsen and we agreed that no templates should be inside the invenio-mail module. The base templates should go in invenio-theme, just like the others base templates.
